"""initial schema

Revision ID: 02e547fa6cf4
Revises: 
Create Date: 2026-08-14 19:23:54.393134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '02e547fa6cf4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('rol', sa.Enum('admin', 'agente_soporte', 'solicitante', name='user_role'), nullable=False),
    sa.Column('departamento', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('assets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('tipo', sa.String(length=100), nullable=False),
    sa.Column('numero_serie', sa.String(length=100), nullable=False),
    sa.Column('ubicacion', sa.String(length=255), nullable=True),
    sa.Column('asignado_a', sa.UUID(), nullable=True),
    sa.Column('estado', sa.Enum('activo', 'en_reparacion', 'dado_de_baja', name='asset_estado'), nullable=False),
    sa.ForeignKeyConstraint(['asignado_a'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_serie')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entidad_tipo', sa.String(length=100), nullable=False),
    sa.Column('entidad_id', sa.UUID(), nullable=False),
    sa.Column('accion', sa.String(length=255), nullable=False),
    sa.Column('realizado_por', sa.UUID(), nullable=False),
    sa.Column('fecha', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['realizado_por'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tickets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('titulo', sa.String(length=500), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('estado', sa.Enum('abierto', 'en_progreso', 'resuelto', 'cerrado', name='ticket_estado'), nullable=False),
    sa.Column('prioridad', sa.Enum('baja', 'media', 'alta', 'critica', name='ticket_prioridad'), nullable=False),
    sa.Column('categoria_id', sa.UUID(), nullable=False),
    sa.Column('solicitante_id', sa.UUID(), nullable=False),
    sa.Column('agente_id', sa.UUID(), nullable=True),
    sa.Column('activo_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['activo_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['agente_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['categoria_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['solicitante_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attachments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ticket_id', sa.UUID(), nullable=False),
    sa.Column('url_archivo', sa.String(length=1000), nullable=False),
    sa.Column('subido_por', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['subido_por'], ['users.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ticket_id', sa.UUID(), nullable=False),
    sa.Column('autor_id', sa.UUID(), nullable=False),
    sa.Column('contenido', sa.Text(), nullable=False),
    sa.Column('es_interno', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['autor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comments')
    op.drop_table('attachments')
    op.drop_table('tickets')
    op.drop_table('audit_log')
    op.drop_table('assets')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('categories')
    # ### end Alembic commands ###
