"""fase4_sla_breach_notified

Revision ID: 4b43d24a7d1a
Revises: bb9c745f8db2
Create Date: 2026-08-19 13:52:36.207008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '4b43d24a7d1a'
down_revision: Union[str, None] = 'bb9c745f8db2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('sla_breach_notified', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'sla_breach_notified')
    # ### end Alembic commands ###
