"""fase3_tickets_sla_attachments_r2

Revision ID: bb9c745f8db2
Revises: 0d962933c5fb
Create Date: 2026-08-18 17:23:17.568457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'bb9c745f8db2'
down_revision: Union[str, None] = '0d962933c5fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attachments', sa.Column('s3_key', sa.String(length=1000), nullable=True))
    op.add_column('attachments', sa.Column('nombre_archivo', sa.String(length=500), nullable=True))
    op.add_column('attachments', sa.Column('mime_type', sa.String(length=100), nullable=True))
    op.add_column('attachments', sa.Column('confirmado', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.alter_column('attachments', 'url_archivo',
               existing_type=sa.VARCHAR(length=1000),
               nullable=True)
    op.add_column('tickets', sa.Column('sla_response_due_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tickets', sa.Column('sla_resolution_due_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tickets', sa.Column('first_response_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'first_response_at')
    op.drop_column('tickets', 'sla_resolution_due_at')
    op.drop_column('tickets', 'sla_response_due_at')
    op.alter_column('attachments', 'url_archivo',
               existing_type=sa.VARCHAR(length=1000),
               nullable=False)
    op.drop_column('attachments', 'confirmado')
    op.drop_column('attachments', 'mime_type')
    op.drop_column('attachments', 'nombre_archivo')
    op.drop_column('attachments', 's3_key')
    # ### end Alembic commands ###
