"""fase6_category_prioridad_sugerida

Revision ID: d0dbd2dc984f
Revises: 4b43d24a7d1a
Create Date: 2026-08-20 16:08:52.545011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd0dbd2dc984f'
down_revision: Union[str, None] = '4b43d24a7d1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('prioridad_sugerida', sa.String(length=20), server_default='media', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'prioridad_sugerida')
    # ### end Alembic commands ###
